openapi: 3.0.3
info:
  title: Elevation API
  description: >-
    **Note**: <ol> <li> The response listed in the below documentation is ONLY indicative of the overall capabilities of MapmyIndia's Search APIs. </li><li> Not all response parameters mentioned in the below documentation is assured to be present in all the use-cases. The response of any of the below search API is thus, dependent on the use-case agreed upon between MapmyIndia & it's API consumer. </i><li> For any further clarifications on what all of the response structure is available for your use case, please contact your business relationship manager or contact MapmyIndia API support.</li><li> <strong>PREMIUM APIs</strong> are not available for evalulation on signup. To get access, please contact API Support.</li></ol>
  termsOfService: 'https://www.mapmyindia.com/api/terms-&-conditions'
  version: 1.0.0
  license:
    name: MapmyIndia License Key Signup
    url: https://www.mapmyindia.com/api/
  contact:
    name: MapmyIndia API Support
    email: apisupport@mapmyindia.com
    url: https://www.mapmyindia.com/api/
servers:
  - url: https://apis.mapmyindia.com/advancedmaps/v1
    description: 'Live Prod server for Elevation API'
paths:
  /{REST_KEY}/elevation:
      get:
        tags:
          - Elevation API
        description: >-
          The Elevation API provides elevation data above the sea level for location on Earth’s surface. The Elevation API allows you to retrieve sampled elevation data along a path. This API can be useful for biking, trucking & in other routing applications.
        summary: >-
          Elevation API
        operationId: ElevationAPI
        parameters: 
        - name: REST_KEY
          in: path
          description: 'The REST API licence key allocated to you by signing into our services and registering yourself as a developer.'
          allowEmptyValue: false
          required: true
          example: "threstapikeywillcomeheretoaccess"
          schema:
            type: string
        - name: locations
          in: query
          description: >-
           The location coordinates are expressed in pairs of (latitude,longitude|latitude,longitude)
          allowEmptyValue: false
          required: true
          example: "9.538350,76.998825|8.930019,76.655587" 
          schema:
            type: string
        responses:
          '200':
            description: OK
            content:
              application/json:
                schema:
                 $ref: '#/components/schemas/RG1'
          '204':
            description: Not found
          '400':
            description: Bad request
          '401':
            description: API access denied
          '403':
            description: Forbidden
          '500':
            description: Something went wrong
          '503':
            description: Internal server error
        deprecated: false
components:
 schemas:
  RG1:
      title: Elevation API Results
      description: The result object which contains the Elevation API results.
      type: object
      required:
        - responseCode
        - version
        - results
      properties:
        responseCode:
          type: integer
          description: This shows the response code of the results.
          format: integer
          example: 200
        version:
          type: string
          description: This shows the API version
          format: string
          example: '211.18'
        results:
          type: array
          items: 
            $ref: '#/components/schemas/RG2'
          description: The object contains the results of the Elevation API.
  RG2:
      title: Elevation API results object 
      description: The result object which contains the Elevation API results.
      type: object
      required: 
       - longitude
       - latitude
       - elevation
      properties:
        longitude:
         type: integer
         description: 'It shows us the longitude of the location serached'
         format: double
         example: 76.998825   
        latitude:
         type: integer
         description: 'It shows us the latitude of the location searched'
         format: double
         example: 9.53835
        elevation:
         type: integer
         description: 'The elevation of the location' 
         format: string
         example: 523

