openapi: 3.0.3
info:
  title: Address Standardization API
  description: >-
    This APIs follow OAuth2 based security. **To know more on how to create your authorization tokens, please use our authorization token URL. More details available**  [here](https://www.mapmyindia.com/api/advanced-maps/doc/authentication-api.php).<br><br>The API leverages OAuth 2.0 based security. Hence, the developer would need to send a request for access token using their client_id and client_secret to the OAuth API. Once validated from the OAuth API, the access_token and the token_type need to be sent as Authorization header with the value: "{`token_type`} {`access_token`}”. <br><strong>Authorization</strong>: `token_type` `access_token`.<br><br> **Note**: <ol> <li> The response listed in the below documentation is ONLY indicative of the overall capabilities of MapmyIndia's Search APIs. </li><li> Not all response parameters mentioned in the below documentation is assured to be present in all the use-cases. The response of any of the below search API is thus, dependent on the use-case agreed upon between MapmyIndia & it's API consumer. </i><li> For any further clarifications on what all of the response structure is available for your use case, please contact your business relationship manager or contact MapmyIndia API support.</li><li> <strong>PREMIUM APIs/Parameters</strong> are not available for evalulation on signup. To get access, please contact API Support.</li></ol>
  termsOfService: 'https://www.mapmyindia.com/api/terms-&-conditions'
  version: 1.0.0
  license:
    name: MapmyIndia License Key Signup
    url: https://www.mapmyindia.com/api/
  contact:
    name: MapmyIndia API Support
    email: apisupport@mapmyindia.com
    url: https://www.mapmyindia.com/api/
servers:
  - url: 'https://atlas.mapmyindia.com'
    description: 'Live Prod server for OAuth 2 based APIs'
security: 
  - BearerAuth: []
paths:
  /api/places/woodpecker:
      get:
        tags:
          - Address Standardization API
        description: >-
          Address Standardization API is a process to convert the non formatted address into the user readable format by omitting unnecessary information in the address. MapmyIndia address standardization API provides real addresses along with admin and other information.<br>This APIs follow OAuth2 based security. **To know more on how to create your authorization tokens, please use our authorization token URL. More details available**  [here](https://www.mapmyindia.com/api/advanced-maps/doc/authentication-api.php).
          <p style=text-align:right><strong><a href="https://www.mapmyindia.com/api/advanced-maps/woodpecker_demo/">Live Demo</a> </p>
        summary: >-
          Address Standardization API
        operationId: WoodpeckerAPI
        servers:
        - url: https://atlas.mapmyindia.com
          description: 'Live Prod server for OAuth 2 based APIs'
        parameters:
          # - name: Authorization
          #   in: header
          #   description: >-
          #     Authorization header with the value: “{token_type} {access_token}”. <br> Please generate your token from token generation API before calling this API.
          #   required: true
          #   allowEmptyValue: false
          #   schema:
          #     type: string
          #   example: "bearer 0XXXXXXf-dXX0-4XX0-8XXa-eXXXXXXXXXX6"
          - name: address
            in: query
            description: 'The full human readable address that needs to be standardized'
            schema:
              type: string
            allowEmptyValue: false
            required: true
            example: '237 Okhla industrial estate phase 3 new Delhi, Delhi 110020'
          - name: bias
            in: query
            description: 'parameter value can be set to get the bias result towards the urban or rural side. (Default is 1.5 : urban). Where 1 is neutral and < 1 is rural biased and > 1 is Urban biased.'
            allowEmptyValue: false
            example: 1.5
            schema:
              type: number
        responses:
          '200':
            description: OK
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/WoodpeckerResults'
          '204':
            description: Not found
          '400':
            description: Bad request
          '401':
            description: API access denied
          '403':
            description: Forbidden
          '500':
            description: Something went wrong
          '503':
            description: Internal server error
        deprecated: false
components:
  schemas:
    WoodpeckerResults:
      title: Woodpecker Result
      description: The result object which contains the Address Standardization API results.
      type: object
      required: 
        - inputAddress
        - remainingAddress
        - referentialInformation
        - addressInformation
      properties:
        inputAddress:
          type: string
          description: this is the address entered by the user.
          format: string
          example: '237, MapmyIndia Head Office, Okhla Phase 3, New Delhi, Delhi 110010'
        remainingAddress:
          type: string
          description: this is the address striked out by the API.
          format: string
          example: 'mapmyindia head office, okhla new'
        referentialInformation:
          $ref: '#/components/schemas/WP1'
        addressInformation:
          $ref: '#/components/schemas/WP3'
    WP1:
      title: Woodpecker Referential Information
      description: The result object which contains the Address Standardization API results.
      type: object
      required:
        - pincodes
        - floors
        - roads
        - postOffices
        - careOfs
        - landmarks
        - houseNumbers
      properties:
        pincodes:
          type: string
          description: PIN code tagged from input address if found any.
          format: string
          example: '110010'
        floors:
          type: string
          description: Floor info tagged from input address if found any.
          format: string
          example: 'Floor No 1'
        roads:
          type: string
          description: Road tagged from the input address if found any.
          format: string
          example: 'Okhla Road'
        postOffices:
          type: string
          description: Post offices tagged from the input address if found any.
          format: string
          example: ''
        careOfs:
          type: string
          description: Care of (C/O) tagged from the input address if found any.
          format: string
          example: ''
        landmarks:
          type: string
          description: Landmark tagged from the input address if found any.
          format: string
          example: ''
        houseNumbers:
          description: House number information tagged from the input address if found any.
          $ref: '#/components/schemas/WP2'
    WP2:
      title: House Numbers Array
      description: The result object which contains the House Number Arrays of Woodpecker API.
      type: object
      required:
        - prefix
        - houseNo
        - formatted
      properties:
        prefix:
          type: string
          description: ''
          format: string
          example: ''
        houseNo:
          type: string
          description: ''
          format: string
          example: '237'
        formatted:
          type: string
          description: ''
          format: string
          example: '237'
    WP3:
      title: Address Information Object
      description: The result object which contains the Address Standardization API results.
      type: object
      required:
        - adminDetails
        - adminPattern
      properties:
        adminDetails:
          $ref: '#/components/schemas/WP4'
        adminPattern:
          type: array
          items:
            type: string
          example:
            - "state"
            - "city"
            - "locality"
            - "subLocality"
    WP4:
      title: Admin Details of Woodpecker API
      description: The result object which contains the Admin Details of Address Standardization API results
      type: object
      required:
        - state
        - locality
        - city
        - sublocality
        - subsublocality
      properties:
        state:
          $ref: '#/components/schemas/WP5'
        locality:
          $ref: '#/components/schemas/WP6'
        city:
          $ref: '#/components/schemas/WP7'
        sublocality:
          $ref: '#/components/schemas/WP8'
        subsublocality:
          $ref: '#/components/schemas/WP9'
    WP5:
      title: State Original Name
      type: object
      required:
        - originalName
      properties:
        originalName:
          type: string
          description: ''
          format: string
          example: 'Delhi'
    WP6:
      title: locality Original Name
      type: object
      required:
        - originalName
      properties:
        originalName:
          type: string
          description: ''
          format: string
          example: 'New Moti Nagar'
    WP7:
      title: city Original Name
      type: object
      required:
        - originalName
      properties:
        originalName:
          type: string
          description: ''
          format: string
          example: 'New Delhi'
    WP8:
      title: sublocality Original Name
      type: object
      required:
        - originalName
      properties:
        originalName:
          type: string
          description: ''
          format: string
          example: 'Phase 3'
    WP9:
      title: subsublocality Original Name
      type: object
      required:
        - originalName
      properties:
        originalName:
          type: string
          description: ''
          format: string
          example: 'Okhla'
  securitySchemes:
    BearerAuth: 
      type: http
      scheme: bearer
      bearerFormat: 'bearer 0XXXXXXf-dXX0-4XX0-8XXa-eXXXXXXXXXX6'